CREATE TABLE usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    clave VARCHAR(255) NOT NULL,
    rol ENUM('ROLE_ADMIN', 'ROLE_USER_MEDIC', 'ROLE_USER_PATIENT') NOT NULL,
    CONSTRAINT UC_usuarios_login UNIQUE (login)
);
